package cmd

import (
	"fmt"
	"os"

	"github.com/provnai/attest/pkg/bridge"
	"github.com/spf13/cobra"
)

var identityCmd = &cobra.Command{
	Use:   "identity",
	Short: "Show current agent identity",
	Long:  `Show the cryptographic identity ID generated by the Rust security core.`,
	Run: func(cmd *cobra.Command, args []string) {
		agent := bridge.NewAttestAgent()
		defer agent.Free()

		id := agent.GetID()
		if id == "" {
			fmt.Println("Error: Failed to fetch agent identity from Rust core")
			os.Exit(1)
		}

		if jsonOutput {
			fmt.Printf("{\"id\": \"%s\"}\n", id)
		} else {
			fmt.Printf("Agent Identity: %s\n", id)
		}
	},
}
